### ISSUE TITLE
autoplay feature

### ISSUE THREAD

**Issue by nileshparmar1979** [Oil3/Webm-QuickLook-Plug-In#2]
Any change an autoplay upon hitting spacebar could be available please.

**Comment by Oil3** [comment]
it might be possible without interfering with quicklook's own (default) spacebar, i'll try to find a way.  
Meanwhile, you can always do:
 _a click in the middle of the video_ to start playing the video  (also click to pause);.

And while previewing, there is also _right click_ for play/pause/

@nileshparmar1979  ideally for you, if spacebar puts the video in "preview" + starts playing, that ?

**Comment by nileshparmar1979** [comment]
Thanks @Oil3, yes, so it would be as if you would quick look a mp4 file on a mac. Spacebar>preview starts with sound.

**Comment by nileshparmar1979** [comment]
The UI could be larger too as it seems it is very small currently. Here is a screenshot to compare to a normal QuickLook
![ScreenShot](https://github.com/user-attachments/assets/9bf31255-bcb6-4178-9fa3-b6e52d584d15)
![AppleQL](https://github.com/user-attachments/assets/e1f7e6fd-5111-42d9-824e-86f047280b6c)

**Comment by nileshparmar1979** [comment]
Thank you. It now works natively and now sits within my user library Quicklook folder.
![ScreenShot](https://github.com/user-attachments/assets/0d7d5ebf-ee05-465d-a8ac-2634209b111e)

**Comment by Oil3** [comment]
glad you like it!
thanks for the input: i'll aim to align the plug-in with the native video previewer.
